[package]
name = "netlink-buildtools"
version = "0.1.0"
authors = ["Erik Svensson <erik.public@gmail.com>"]

[dependencies]
clap = "2"
regex = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
